### ISSUE TITLE
Message keyLength error

### ISSUE THREAD

**Issue by LinuxPlusPlus** [adobe-research/libkafka#2]
There is a problem in Message::Message(Packet *packet, long int offset) when keyLength return -1; I try to fix that in my fork. Can you think over that?

**Comment by DavidTompkins** [comment]
Is this the same as issue #1 ? Fixed in v 0.4.0?

**Comment by LinuxPlusPlus** [comment]
No, Fixed in v0.4.0 on issue #1 just avoid reading -1 buffer. But when produced message has no key, keyLength is -1, I found that Message::getWireFormatSize result missing 1, becasue "size += sizeof(int) + this->keyLength;"(Message.cpp:157), actully keyLenght should be 0, not -1.

**Comment by LinuxPlusPlus** [comment]
Oh, I think it twice, maybe you're right, it's the same as issue #1 . But Fixed in V0.4.0 not really fixed.
